import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoilRootProvider from '@/providers/only-rayout/recoil-root.provider'
import RootLayoutWrapProvider from '@/providers/only-rayout/root-rayout-wrap.provider'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gradient-to-r from-purple-300 to-pink-100` }>
        <RecoilRootProvider>
          <RootLayoutWrapProvider>{children}</RootLayoutWrapProvider>
        </RecoilRootProvider>
      </body>
    </html>
  )
}
