import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import RecoilRootProvider from '@/providers/only-rayout/recoil-root.provider'
import RootLayoutWrapProvider from '@/providers/only-rayout/root-rayout-wrap.provider'
import { ReactNode } from 'react'
import {RecoilRoot} from "recoil";
import {GithubModal} from "@/components/modal/github.modal";
import {BlogModal} from "@/components/modal/blog.modal";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
        <body
            className={`${inter.className} flex flex-col h-screen bg-gradient-to-r from-purple-300 to-pink-100 dark:from-purple-700 to-pink-500`}
        >
          <RecoilRootProvider>
            <RootLayoutWrapProvider>{children}</RootLayoutWrapProvider>
          </RecoilRootProvider>
        </body>
    </html>
  )
}
